import type { AnalysisReport, AnalysisRequest } from "@/types/analysis"

export interface Demo {
  request: AnalysisRequest
  report: AnalysisReport
}

export interface DemoEntry {
  id: string
  label: string
  load: () => Promise<Demo>
}

// Generated by backend/scripts/generate_demo_reports.py. Each loads on first view.
export const DEMOS: DemoEntry[] = [
  { id: "package-json", label: "package.json", load: () => import("./package-json.json").then(asDemo) },
  { id: "requirements-txt", label: "requirements.txt", load: () => import("./requirements-txt.json").then(asDemo) },
  { id: "log4j", label: "log4j-core", load: () => import("./log4j.json").then(asDemo) },
]

function asDemo(module: { default: unknown }): Demo {
  return module.default as Demo
}
