import { useEffect, useState } from "react"

import type { AnalysisReport, AnalysisRequest } from "@/types/analysis"

export interface Demo {
  request: AnalysisRequest
  report: AnalysisReport
}

// Generated by backend/scripts/generate_demo_reports.py. Each loads on first use.
const LOADERS = {
  "package-json": () => import("./package-json.json"),
  "requirements-txt": () => import("./requirements-txt.json"),
  log4j: () => import("./log4j.json"),
}

export type DemoId = keyof typeof LOADERS

export const DEMOS: { id: DemoId; label: string }[] = [
  { id: "package-json", label: "package.json" },
  { id: "requirements-txt", label: "requirements.txt" },
  { id: "log4j", label: "log4j-core" },
]

const cache = new Map<DemoId, Promise<Demo>>()

function loadDemo(id: DemoId): Promise<Demo> {
  let demo = cache.get(id)
  if (!demo) {
    demo = LOADERS[id]().then((module) => module.default as unknown as Demo)
    cache.set(id, demo)
  }
  return demo
}

export function useDemo(id: DemoId): Demo | null {
  const [loaded, setLoaded] = useState<{ id: DemoId; demo: Demo } | null>(null)

  useEffect(() => {
    let cancelled = false
    void loadDemo(id).then((demo) => {
      if (!cancelled) setLoaded({ id, demo })
    })
    return () => {
      cancelled = true
    }
  }, [id])

  return loaded?.id === id ? loaded.demo : null
}
